"""Build a Windows installer for DCS Command Palette using Inno Setup.

Usage:
    python build_installer.py

Steps:
1. Runs PyInstaller to create dist/dcs-command-palette/
2. Generates an Inno Setup .iss script
3. Runs Inno Setup compiler (ISCC.exe) to produce the installer .exe

Requirements:
    - PyInstaller: pip install pyinstaller
    - Inno Setup 6: https://jrsoftware.org/isdl.php
      (default install path, or set ISCC_PATH env var)

Produces:
    dist/DCS-Command-Palette-v{version}-Setup.exe
"""
from __future__ import annotations

import os
import subprocess
import sys

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
DIST_DIR = os.path.join(PROJECT_DIR, "dist", "dcs-command-palette")
ISS_PATH = os.path.join(PROJECT_DIR, "dist", "installer.iss")

# Common Inno Setup locations
_ISCC_CANDIDATES = [
    os.environ.get("ISCC_PATH", ""),
    os.path.join(os.environ.get("LOCALAPPDATA", ""), "Programs", "Inno Setup 6", "ISCC.exe"),
    r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
    r"C:\Program Files\Inno Setup 6\ISCC.exe",
]


def _find_iscc() -> str | None:
    """Find the Inno Setup compiler (ISCC.exe)."""
    for path in _ISCC_CANDIDATES:
        if path and os.path.isfile(path):
            return path
    return None


def _get_version() -> str:
    """Read version from pyproject.toml."""
    try:
        toml_path = os.path.join(PROJECT_DIR, "pyproject.toml")
        with open(toml_path, encoding="utf-8") as f:
            for line in f:
                if line.strip().startswith("version"):
                    return line.split("=", 1)[1].strip().strip('"').strip("'")
    except (OSError, IndexError):
        pass
    return "0.0.0"


def _generate_iss(version: str) -> str:
    """Generate the Inno Setup .iss script content."""
    return f"""; DCS Command Palette Installer
; Auto-generated by build_installer.py — do not edit manually.

#define MyAppName "DCS Command Palette"
#define MyAppVersion "{version}"
#define MyAppPublisher "Juan Jose Alvarez Martinez"
#define MyAppURL "https://github.com/juanjux/dcs-command-palette"
#define MyAppExeName "dcs-command-palette.exe"

[Setup]
AppId={{{{B8F3A2D1-7C4E-4F8A-9B1D-3E5F7A8C2D4E}}}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
AppPublisherURL={{#MyAppURL}}
AppSupportURL={{#MyAppURL}}/issues
DefaultDirName={{code:GetDefaultDir}}
DefaultGroupName={{#MyAppName}}
LicenseFile={os.path.join(PROJECT_DIR, "LICENSE")}
OutputDir={os.path.join(PROJECT_DIR, "dist")}
OutputBaseFilename=DCS-Command-Palette-v{version}-Setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayName={{#MyAppName}}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"
Name: "installhook"; Description: "Install DCS Lua hook (auto-start with missions)"; GroupDescription: "DCS Integration:"; Flags: checkedonce

[Files]
; Main application files (everything from PyInstaller dist)
Source: "{DIST_DIR}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

; Lua hook source (for the install task)
Source: "{os.path.join(PROJECT_DIR, 'src', 'lua', 'dcs_command_palette_hook.lua')}"; DestDir: "{{app}}"; Flags: ignoreversion

[Icons]
Name: "{{group}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"
Name: "{{group}}\\Uninstall {{#MyAppName}}"; Filename: "{{uninstallexe}}"
Name: "{{userdesktop}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; Tasks: desktopicon

[Run]
; Offer to launch after install
Filename: "{{app}}\\{{#MyAppExeName}}"; Description: "Launch DCS Command Palette"; Flags: nowait postinstall skipifsilent

[Code]
// Pascal Script for custom install logic

function GetDefaultDir(Param: String): String;
var
  Path: String;
begin
  // Default to Saved Games\DCS\dcs-command-palette
  Path := ExpandConstant('{{%USERPROFILE}}\\Saved Games\\DCS');
  if DirExists(Path) then
  begin
    Result := Path + '\\dcs-command-palette';
    Exit;
  end;
  // Try OpenBeta
  Path := ExpandConstant('{{%USERPROFILE}}\\Saved Games\\DCS.openbeta');
  if DirExists(Path) then
  begin
    Result := Path + '\\dcs-command-palette';
    Exit;
  end;
  // Fallback
  Result := ExpandConstant('{{%USERPROFILE}}\\Saved Games\\DCS\\dcs-command-palette');
end;

function GetDCSSavedGamesPath(): String;
var
  Path: String;
begin
  // Try standard DCS path
  Path := ExpandConstant('{{%USERPROFILE}}\\Saved Games\\DCS');
  if DirExists(Path) then
  begin
    Result := Path;
    Exit;
  end;

  // Try OpenBeta
  Path := ExpandConstant('{{%USERPROFILE}}\\Saved Games\\DCS.openbeta');
  if DirExists(Path) then
  begin
    Result := Path;
    Exit;
  end;

  Result := '';
end;

procedure InstallLuaHook();
var
  DCSPath, HooksDir, HookSrc, HookDest: String;
begin
  DCSPath := GetDCSSavedGamesPath();
  if DCSPath = '' then
  begin
    Log('DCS Saved Games directory not found — skipping hook install');
    Exit;
  end;

  HooksDir := DCSPath + '\\Scripts\\Hooks';
  ForceDirectories(HooksDir);

  HookSrc := ExpandConstant('{{app}}\\dcs_command_palette_hook.lua');
  HookDest := HooksDir + '\\dcs_command_palette_hook.lua';

  if FileCopy(HookSrc, HookDest, False) then
    Log('Lua hook installed to: ' + HookDest)
  else
    Log('Failed to install Lua hook to: ' + HookDest);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    if IsTaskSelected('installhook') then
      InstallLuaHook();
  end;
end;

// On uninstall, remove the Lua hook
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DCSPath, HookPath: String;
begin
  if CurUninstallStep = usPostUninstall then
  begin
    DCSPath := GetDCSSavedGamesPath();
    if DCSPath <> '' then
    begin
      HookPath := DCSPath + '\\Scripts\\Hooks\\dcs_command_palette_hook.lua';
      if FileExists(HookPath) then
      begin
        DeleteFile(HookPath);
        Log('Lua hook removed: ' + HookPath);
      end;
    end;
  end;
end;
"""


def build_pyinstaller() -> bool:
    """Run PyInstaller to create the dist folder."""
    print("=" * 60)
    print("  Step 1/2: Building .exe with PyInstaller")
    print("=" * 60)
    print()

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--name", "dcs-command-palette",
        "--noconsole",
        "--noconfirm",
        "--add-data", os.path.join("src", "lua", "dcs_command_palette_hook.lua") + f"{os.pathsep}.",
        "--hidden-import", "src.installer.wizard",
        "--hidden-import", "src.bios.installer",
        "--hidden-import", "pynput.keyboard._win32",
        "--hidden-import", "pynput.mouse._win32",
        "--collect-all", "pygame",
        "main.py",
    ]

    result = subprocess.run(cmd, cwd=PROJECT_DIR)
    if result.returncode != 0:
        print("ERROR: PyInstaller build failed!")
        return False

    print("\nPyInstaller build complete.")
    return True


def build_installer() -> bool:
    """Generate and compile the Inno Setup installer."""
    print()
    print("=" * 60)
    print("  Step 2/2: Creating installer with Inno Setup")
    print("=" * 60)
    print()

    iscc = _find_iscc()
    if not iscc:
        print("ERROR: Inno Setup compiler (ISCC.exe) not found!")
        print("Install Inno Setup 6 from https://jrsoftware.org/isdl.php")
        print("Or set the ISCC_PATH environment variable to the ISCC.exe path.")
        return False

    version = _get_version()
    print(f"Version: {version}")
    print(f"ISCC: {iscc}")

    # Generate the .iss file
    iss_content = _generate_iss(version)
    with open(ISS_PATH, "w", encoding="utf-8") as f:
        f.write(iss_content)
    print(f"Generated: {ISS_PATH}")

    # Compile
    result = subprocess.run([iscc, ISS_PATH], cwd=PROJECT_DIR)
    if result.returncode != 0:
        print("ERROR: Inno Setup compilation failed!")
        return False

    output = os.path.join(PROJECT_DIR, "dist", f"DCS-Command-Palette-v{version}-Setup.exe")
    if os.path.isfile(output):
        size_mb = os.path.getsize(output) / (1024 * 1024)
        print(f"\nInstaller created: {output}")
        print(f"Size: {size_mb:.1f} MB")
    else:
        print(f"\nWARNING: Expected output not found at {output}")

    return True


def main() -> None:
    if not build_pyinstaller():
        sys.exit(1)

    if not build_installer():
        sys.exit(1)

    print()
    print("=" * 60)
    print("  Build complete!")
    print("=" * 60)
    version = _get_version()
    print(f"\n  Installer: dist/DCS-Command-Palette-v{version}-Setup.exe")
    print(f"  ZIP dist:  dist/dcs-command-palette/")
    print()
    print("  Upload the installer .exe to GitHub releases.")
    print()


if __name__ == "__main__":
    main()
